alter table "_realtime"."tenants" drop column "enable_authorization";

alter table "_realtime"."tenants" drop column "jwt_jwks";


create table "public"."bids" (
    "created_at" timestamp with time zone default now(),
    "json" jsonb not null,
    "id" text not null,
    "akash_price_usd" numeric,
    "block_height" numeric not null
);


alter table "public"."bids" enable row level security;

create table "public"."nodes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "lease_first_block" numeric not null,
    "lease_last_block" numeric,
    "dseq" numeric not null,
    "gseq" numeric not null,
    "wallet_address" text not null,
    "akash_provider" text not null default '[]'::text,
    "bid_id" text not null,
    "json" jsonb not null,
    "provider_domain" text not null,
    "provider_uris" text[],
    "price_per_block" numeric not null,
    "resources" jsonb not null,
    "state" numeric not null default '-1'::numeric,
    "ports" text[],
    "sdl_id" bigint
);


alter table "public"."nodes" enable row level security;

create table "public"."sdl" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "yml_json" jsonb,
    "name" text not null,
    "vasi.ai" numeric not null,
    "gcp" numeric not null,
    "aws" numeric not null
);


alter table "public"."sdl" enable row level security;

CREATE UNIQUE INDEX bids_bid_id_key ON public.bids USING btree (id);

CREATE UNIQUE INDEX bids_pkey ON public.bids USING btree (id);

CREATE UNIQUE INDEX nodes_bid_id_key ON public.nodes USING btree (bid_id);

CREATE UNIQUE INDEX nodes_pkey ON public.nodes USING btree (id);

CREATE UNIQUE INDEX sdl_name_key ON public.sdl USING btree (name);

CREATE UNIQUE INDEX sdl_pkey ON public.sdl USING btree (id);

alter table "public"."bids" add constraint "bids_pkey" PRIMARY KEY using index "bids_pkey";

alter table "public"."nodes" add constraint "nodes_pkey" PRIMARY KEY using index "nodes_pkey";

alter table "public"."sdl" add constraint "sdl_pkey" PRIMARY KEY using index "sdl_pkey";

alter table "public"."bids" add constraint "bids_bid_id_key" UNIQUE using index "bids_bid_id_key";

alter table "public"."nodes" add constraint "nodes_bid_id_key" UNIQUE using index "nodes_bid_id_key";

alter table "public"."nodes" add constraint "public_nodes_bid_id_fkey" FOREIGN KEY (bid_id) REFERENCES bids(id) ON UPDATE RESTRICT ON DELETE RESTRICT not valid;

alter table "public"."nodes" validate constraint "public_nodes_bid_id_fkey";

alter table "public"."nodes" add constraint "public_nodes_sdl_id_fkey" FOREIGN KEY (sdl_id) REFERENCES sdl(id) ON UPDATE RESTRICT ON DELETE RESTRICT not valid;

alter table "public"."nodes" validate constraint "public_nodes_sdl_id_fkey";

alter table "public"."sdl" add constraint "sdl_name_key" UNIQUE using index "sdl_name_key";

grant delete on table "public"."bids" to "anon";

grant insert on table "public"."bids" to "anon";

grant references on table "public"."bids" to "anon";

grant select on table "public"."bids" to "anon";

grant trigger on table "public"."bids" to "anon";

grant truncate on table "public"."bids" to "anon";

grant update on table "public"."bids" to "anon";

grant delete on table "public"."bids" to "authenticated";

grant insert on table "public"."bids" to "authenticated";

grant references on table "public"."bids" to "authenticated";

grant select on table "public"."bids" to "authenticated";

grant trigger on table "public"."bids" to "authenticated";

grant truncate on table "public"."bids" to "authenticated";

grant update on table "public"."bids" to "authenticated";

grant delete on table "public"."bids" to "service_role";

grant insert on table "public"."bids" to "service_role";

grant references on table "public"."bids" to "service_role";

grant select on table "public"."bids" to "service_role";

grant trigger on table "public"."bids" to "service_role";

grant truncate on table "public"."bids" to "service_role";

grant update on table "public"."bids" to "service_role";

grant delete on table "public"."nodes" to "anon";

grant insert on table "public"."nodes" to "anon";

grant references on table "public"."nodes" to "anon";

grant select on table "public"."nodes" to "anon";

grant trigger on table "public"."nodes" to "anon";

grant truncate on table "public"."nodes" to "anon";

grant update on table "public"."nodes" to "anon";

grant delete on table "public"."nodes" to "authenticated";

grant insert on table "public"."nodes" to "authenticated";

grant references on table "public"."nodes" to "authenticated";

grant select on table "public"."nodes" to "authenticated";

grant trigger on table "public"."nodes" to "authenticated";

grant truncate on table "public"."nodes" to "authenticated";

grant update on table "public"."nodes" to "authenticated";

grant delete on table "public"."nodes" to "service_role";

grant insert on table "public"."nodes" to "service_role";

grant references on table "public"."nodes" to "service_role";

grant select on table "public"."nodes" to "service_role";

grant trigger on table "public"."nodes" to "service_role";

grant truncate on table "public"."nodes" to "service_role";

grant update on table "public"."nodes" to "service_role";

grant delete on table "public"."sdl" to "anon";

grant insert on table "public"."sdl" to "anon";

grant references on table "public"."sdl" to "anon";

grant select on table "public"."sdl" to "anon";

grant trigger on table "public"."sdl" to "anon";

grant truncate on table "public"."sdl" to "anon";

grant update on table "public"."sdl" to "anon";

grant delete on table "public"."sdl" to "authenticated";

grant insert on table "public"."sdl" to "authenticated";

grant references on table "public"."sdl" to "authenticated";

grant select on table "public"."sdl" to "authenticated";

grant trigger on table "public"."sdl" to "authenticated";

grant truncate on table "public"."sdl" to "authenticated";

grant update on table "public"."sdl" to "authenticated";

grant delete on table "public"."sdl" to "service_role";

grant insert on table "public"."sdl" to "service_role";

grant references on table "public"."sdl" to "service_role";

grant select on table "public"."sdl" to "service_role";

grant trigger on table "public"."sdl" to "service_role";

grant truncate on table "public"."sdl" to "service_role";

grant update on table "public"."sdl" to "service_role";

create policy "Enable read access for all users"
on "public"."bids"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."nodes"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."sdl"
as permissive
for select
to public
using (true);



